---
- hosts: localhost
  vars:
    rg_name: Yuta
    subdomain_prefix: voting
    localisation: westus
    ansible_python_interpreter: venv_ansible/bin/python
  connection: local
  tasks:
  - import_tasks: base.yml
  - import_tasks: bastion.yml
  - import_tasks: redis.yml
  - import_tasks: nat.yml
  - name: initialisation du fichier cloud-init
    ansible.builtin.template:
      src: cloud-init.yml.tmpl
      dest: cloud-init.yml
  - import_tasks: gateway.yml
  - import_tasks: vmss.yml

